## Problem 2 - Data manipulation and selection (*9 points*)

In this problem you will clean the data from our data file by removing no-data values, convert temperature values in Fahrenheit to Celsius, and split the data into separate datasets using the weather station identification code. We will start this problem by cleaning and converting our temperature data. Please perform the tasks below by writing your code into the codeblocks in each section.

**Notice**: Closely follow the instructions! For example, you should be sure to use **exactly** the same variable names mentioned in the instructions because your answers will be automatically graded, and the tests that grade your answers rely on following the same formatting or variable naming as in the instructions.

**Your score on this problem will be based on following criteria:**

- Creating a new dataframe called `selected` that contains select columns from the data file
- Cleaning the new dataframe by removing no-data values
- Creating a new column for temperatures converted from Fahrenheit to Celsius
- Dividing the data into separate dataframes for the Helsinki Kumpula and Rovaniemi stations
- Saving the new dataframes to CSV files
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem
- Uploading your notebook and data files to your GitHub repository for this week's exercise  

### Part 1 (*0 points*)

The first step for this problem is to again read the data file.

- Use Pandas to read the [data/6153237444115dat.csv](data/6153237444115dat.csv) file into the varaible `data` (you can copy your code from Problem 1).

In [16]:
# Import Pandas and read in the data from csv
import pandas as pd
data=pd.read_csv("data/6153237444115dat.csv", na_values=['*', '**', '***', '****', '*****', '******'])
data.head()
data.tail()

USAF   WBAN  YR--MODAHRMN    DIR   SPD   GUS   CLG  SKC   L   M  ...  \
11689  29980  99999  201708311900  144.0  12.0  20.0  50.0  BKN NaN NaN  ...   
11690  29980  99999  201708312000  137.0  14.0  20.0  40.0  BKN NaN NaN  ...   
11691  29980  99999  201708312100  160.0  13.0   NaN   NaN  BKN NaN NaN  ...   
11692  29980  99999  201708312200  170.0  12.0  21.0  28.0  OVC NaN NaN  ...   
11693  29980  99999  201708312300  192.0  13.0  21.0  19.0  BKN NaN NaN  ...   

          SLP  ALT     STP  MAX  MIN  PCP01  PCP06  PCP24  PCPXX   SD  
11689  1007.7  NaN  1004.7  NaN  NaN    NaN    NaN    NaN    NaN  0.0  
11690  1006.9  NaN  1003.9  NaN  NaN    NaN    NaN    NaN    NaN  0.0  
11691  1006.1  NaN  1003.2  NaN  NaN    NaN    NaN    NaN    NaN  NaN  
11692  1006.1  NaN  1003.1  NaN  NaN    NaN    NaN    NaN    NaN  0.0  
11693  1005.8  NaN  1002.8  NaN  NaN    NaN    NaN    NaN    NaN  0.0  

[5 rows x 33 columns]

### Part 2 (*2 points*)

Next, you can subset the data and remove the no-data values.

 - Create a new variable `selected`
 - Select the columns `USAF`, `YR--MODAHRMN`, `TEMP`, `MAX`, and `MIN` from the `data` dataframe and assign them to the new variable `selected`
 - Remove all rows from `selected` that have NoData in the column `TEMP` using the `dropna()` function

In [23]:
#Select subset
selected = data.loc(axis=1)['USAF', 'YR--MODAHRMN','TEMP', 'MAX','MIN']

#remove rows with missing temp values
selected.dropna(subset=['TEMP'], inplace=True)

In [25]:
# Check your dataframe 
selected.head()



USAF  YR--MODAHRMN  TEMP  MAX  MIN
0  28450  201705010000  31.0  NaN  NaN
1  28450  201705010020  30.0  NaN  NaN
2  28450  201705010050  30.0  NaN  NaN
3  28450  201705010100  31.0  NaN  NaN
4  28450  201705010120  30.0  NaN  NaN

In [40]:
selected.tail()

USAF  YR--MODAHRMN  TEMP  MAX  MIN    Celsius
11689  29980  201708311900  64.0  NaN  NaN  17.777778
11690  29980  201708312000  64.0  NaN  NaN  17.777778
11691  29980  201708312100  64.0  NaN  NaN  17.777778
11692  29980  201708312200  64.0  NaN  NaN  17.777778
11693  29980  201708312300  64.0  NaN  NaN  17.777778

In [26]:
# Check your dataframe 
len(selected)

11691

### Part 3 (*2 points*)

Next, you can convert the temperature values in Fahrenheit to Celsius.

- Create a new column in `selected` called `Celsius`
- Convert the Fahrenheit temperatures from `TEMP` using the conversion formula (below) and store the results in the new `Celsius`column.

$$
\begin{equation}
  T_{\textrm{C}} = (T_{\textrm{F}} - 32)~/~1.8
\end{equation}
$$

- Round the values in the `Celsius` column to have 0 decimals (**do not** create a new column, update the current one)
- Convert the `Celsius` values into integers (**do not** create a new column, update the current one)

In [47]:
#create new column with temp in celsius
selected["Celsius"]=(selected["TEMP"]-32)/1.8

#round to 0 decimal places and convert to integer
selected["Celsius"]=selected["Celsius"].round(0).astype(int)

In [48]:
# Check your dataframe
selected.head()


USAF  YR--MODAHRMN  TEMP  MAX  MIN  Celsius
0  28450  201705010000  31.0  NaN  NaN       -1
1  28450  201705010020  30.0  NaN  NaN       -1
2  28450  201705010050  30.0  NaN  NaN       -1
3  28450  201705010100  31.0  NaN  NaN       -1
4  28450  201705010120  30.0  NaN  NaN       -1

In [49]:
# Check that the temperatures are converted into interger type
ok_(selected['Celsius'].dtype == 'int32' or selected['Celsius'].dtype == 'int64')

NameError: name 'ok_' is not defined

### Part 4 (*2 points*)

Your next task is to divide `selected` into two separate dataframes. Please use the given variable names and write your answer to the codeblock below.

- Select all rows from the `selected` DataFrame with the `USAF` code `29980` into a variable called `kumpula`
- Select all rows from the `selected` DataFrame with the `USAF` code `28450` into a variable called `rovaniemi`

In [51]:
#new dataframe kumpula
kumpula = selected.loc[selected['USAF']==29980]

#new dataframe rovaniemi
rovaniemi = selected.loc[selected['USAF']==28450]



In [52]:
# Check the dataframe
print("Kumpula: \n", kumpula.head(), "\n")


Kumpula: 
        USAF  YR--MODAHRMN  TEMP  MAX  MIN  Celsius
8770  29980  201705010000  37.0  NaN  NaN        3
8771  29980  201705010100  37.0  NaN  NaN        3
8772  29980  201705010200  37.0  NaN  NaN        3
8773  29980  201705010300  37.0  NaN  NaN        3
8774  29980  201705010400  39.0  NaN  NaN        4 



In [53]:
# Check the dataframe
print("Rovaniemi: \n", rovaniemi.head(), "\n")


Rovaniemi: 
     USAF  YR--MODAHRMN  TEMP  MAX  MIN  Celsius
0  28450  201705010000  31.0  NaN  NaN       -1
1  28450  201705010020  30.0  NaN  NaN       -1
2  28450  201705010050  30.0  NaN  NaN       -1
3  28450  201705010100  31.0  NaN  NaN       -1
4  28450  201705010120  30.0  NaN  NaN       -1 



### Part 5 (*3 points*)

Now you can save your selections to csv files.

- Save the `kumpula` DataFrame into the file `Kumpula_temps_May_Aug_2017.csv` (CSV format) 
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Save the `rovaniemi` DataFrame into the file `Rovaniemi_temps_May_Aug_2017.csv` (CSV format) 
    - Separate the columns with commas (`,`)
    - Use only 2 decimals for the floating point numbers
- Upload both of your data files to your Exercise 5 repository

In [58]:
#define filename paths
output_k= "Kumpula_temps_May_Aug_2017.csv"
output_r="Rovaniemi_temps_May_Aug_2017.csv"

#save to csv
kumpula.to_csv(output_k, sep=',')
rovaniemi.to_csv(output_r,sep=',')

In [59]:
#Read-only cell for hidden tests :)

### Problem 2 summary

In the [Exercise 5 summary notebook](Exercise-5-summary.ipynb) you can find a few additional points to consider and two final questions for Problem 2. Please answer those question in [that notebook](Exercise-5-summary.ipynb).

### On to Problem 3

Now you can continue to [Problem 3: Data analysis](Exercise-5-problem-3.ipynb)